"use client"

import { useEffect, useState } from "react"
import { CheckCircle2, Circle, Clock, MoreHorizontal, Plus, Loader2, ListTodo, X, AlignLeft } from "lucide-react"

type TaskStatus = 'planned' | 'in_progress' | 'review' | 'done'

type TaskItem = {
    id: string
    title: string
    description?: string
    status: TaskStatus
    sourceRunId?: string
    sessionKey?: string
    autoGenerated: boolean
    createdAt: number
    updatedAt: number
}

const STATUSES: { id: TaskStatus; label: string; icon: React.ReactNode; color: string; border: string }[] = [
    { id: 'planned', label: 'To Do', icon: <Circle className="w-5 h-5" />, color: 'bg-gray-500/10 text-gray-400', border: 'border-gray-500/20' },
    { id: 'in_progress', label: 'In Progress', icon: <Clock className="w-5 h-5" />, color: 'bg-blue-500/10 text-blue-400', border: 'border-blue-500/20' },
    { id: 'review', label: 'Review', icon: <MoreHorizontal className="w-5 h-5" />, color: 'bg-yellow-500/10 text-yellow-400', border: 'border-yellow-500/20' },
    { id: 'done', label: 'Done', icon: <CheckCircle2 className="w-5 h-5" />, color: 'bg-green-500/10 text-green-400', border: 'border-green-500/20' }
]

export default function TasksPage() {
    const [tasks, setTasks] = useState<TaskItem[]>([])
    const [loading, setLoading] = useState(true)
    const [newTaskTitle, setNewTaskTitle] = useState("")
    const [isAdding, setIsAdding] = useState(false)
    const [selectedTask, setSelectedTask] = useState<TaskItem | null>(null)
    const [sessions, setSessions] = useState<{ sessionKey: string; status: string }[]>([])
    const [newTaskSessionKey, setNewTaskSessionKey] = useState("agent:main:main")
    const [dispatchStatus, setDispatchStatus] = useState<{ id: string, message: string } | null>(null)
    const [draggedTaskId, setDraggedTaskId] = useState<string | null>(null)
    const [dragOverColumn, setDragOverColumn] = useState<TaskStatus | null>(null)
    const [eventTrigger, setEventTrigger] = useState(0)

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const [selectedTaskEvents, setSelectedTaskEvents] = useState<any[] | null>(null)
    const [loadingEvents, setLoadingEvents] = useState(false)

    // Helper to extract readable text from OpenClaw raw event payloads without trimming
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const extractTextFromEvent = (event: any): string => {
        if (!event || !event.payload) return '';
        const payload = event.payload;
        const msg = payload.message || payload.data || payload.input || payload.prompt || payload.query || payload;

        if (typeof msg === 'string') return msg;
        if (msg && typeof msg === 'object') {
            if (typeof msg.text === 'string') return msg.text;
            if (typeof msg.content === 'string') return msg.content;
            if (Array.isArray(msg.content)) {
                return msg.content.map((c: any) => c.text || c.content || '').join('');
            }
            if (Array.isArray(msg.messages)) {
                return msg.messages.map((m: any) => typeof m === 'string' ? m : (m.text || m.content || '')).join('');
            }
        }
        return '';
    }

    const loadTasks = async () => {
        try {
            setLoading(true)
            const [tasksRes, sessionsRes] = await Promise.all([
                fetch('/api/tasks'),
                fetch('/api/monitor/sessions')
            ])
            const tasksData = await tasksRes.json()
            if (tasksData.tasks) {
                setTasks(tasksData.tasks.sort((a: TaskItem, b: TaskItem) => b.createdAt - a.createdAt))
            }
            const sessionsData = await sessionsRes.json()
            if (sessionsData.sessions) {
                // Filter to active/thinking sessions or just keep all for selection
                setSessions(sessionsData.sessions)
            }
        } catch (err) {
            console.error(err)
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        loadTasks()

        const es = new EventSource('/api/monitor/events')
        es.onmessage = (e) => {
            try {
                const data = JSON.parse(e.data)

                // If a task changed status, auto-generated a title, or was created
                if (data.type === 'task_updated' || data.type === 'task_created') {
                    loadTasks()
                }

                // If this is an agent event (stream chunk, new event, etc.)
                if (data.type === 'event' || data.type === 'event_created' || data.runId) {
                    setEventTrigger(prev => prev + 1)
                }
            } catch (err) { }
        }

        return () => es.close()
    }, [])

    // Keep track of the last loaded run ID to avoid flicker when just updating events
    const [lastLoadedRunId, setLastLoadedRunId] = useState<string | null>(null)

    useEffect(() => {
        // Only clear events and show loading if we are switching to a DIFFERENT task
        if (selectedTask?.sourceRunId !== lastLoadedRunId) {
            setSelectedTaskEvents(null)
            setLastLoadedRunId(selectedTask?.sourceRunId || null)
        }

        if (selectedTask?.sourceRunId) {
            if (selectedTask?.sourceRunId !== lastLoadedRunId) {
                setLoadingEvents(true)
            }
            fetch(`/api/monitor/runs/${selectedTask.sourceRunId}/events`)
                .then(res => res.json())
                .then(data => {
                    if (data.events) {
                        // eslint-disable-next-line @typescript-eslint/no-explicit-any
                        const merged: any[] = [];
                        for (const e of data.events) {
                            const rawText = extractTextFromEvent(e).trim();
                            if (!rawText) continue;

                            let mergedIntoExisting = false;

                            // Look back up to 10 recent messages to find a stream to merge into
                            const lookbackLimit = Math.max(0, merged.length - 10);
                            for (let j = merged.length - 1; j >= lookbackLimit; j--) {
                                const prev = merged[j];

                                // Explicit stream ID match or exact duplicate
                                const sameId = (prev.eventId && prev.eventId === e.eventId) || (prev.stream && prev.stream === e.stream);

                                if (sameId || prev.text === rawText) {
                                    if (e.kind === 'chat') prev.kind = 'chat'; // Elevate kind
                                    prev.ts = Math.max(prev.ts, e.ts);
                                    if (rawText.length > prev.text.length) prev.text = rawText;
                                    mergedIntoExisting = true;
                                    break;
                                }

                                // Incoming is an expansion of previous (cumulative chunk)
                                if (rawText.startsWith(prev.text)) {
                                    prev.text = rawText;
                                    if (e.kind === 'chat') prev.kind = 'chat';
                                    prev.ts = Math.max(prev.ts, e.ts);
                                    mergedIntoExisting = true;
                                    break;
                                }

                                // Incoming is a delayed older chunk, ignore it and keep the longer previous chunk
                                if (prev.text.startsWith(rawText)) {
                                    prev.ts = Math.max(prev.ts, e.ts);
                                    mergedIntoExisting = true;
                                    break;
                                }
                            }

                            if (!mergedIntoExisting) {
                                merged.push({ ...e, text: rawText });
                            }
                        }

                        const finalEvents = merged.map(m => ({ ...m, text: m.text.trim() })).filter(m => m.text.length > 0);
                        setSelectedTaskEvents(finalEvents)
                    }
                })
                .catch(console.error)
                .finally(() => setLoadingEvents(false))
        } else {
            // Task has no sourceRunId
            setSelectedTaskEvents(null)
            setLastLoadedRunId(null)
        }
    }, [selectedTask?.sourceRunId, eventTrigger])

    const handleCreateTask = async (e: React.FormEvent) => {
        e.preventDefault()
        if (!newTaskTitle.trim()) return

        setIsAdding(true)
        try {
            const res = await fetch('/api/tasks', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ title: newTaskTitle, sessionKey: newTaskSessionKey })
            })
            if (res.ok) {
                setNewTaskTitle("")
                loadTasks()
            }
        } catch (err) {
            console.error(err)
        } finally {
            setIsAdding(false)
        }
    }

    const handleUpdateStatus = async (id: string, newStatus: TaskStatus, updatedSessionKey?: string) => {
        setTasks(prev => prev.map(t => t.id === id ? { ...t, status: newStatus, sessionKey: updatedSessionKey || t.sessionKey } : t))
        if (selectedTask?.id === id) {
            setSelectedTask(prev => prev ? { ...prev, status: newStatus, sessionKey: updatedSessionKey || prev.sessionKey } : null)
        }

        if (newStatus === 'in_progress') {
            setDispatchStatus({ id, message: 'Dispatching to agent...' })
        }

        try {
            const res = await fetch(`/api/tasks/${id}/status`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ status: newStatus, sessionKey: updatedSessionKey })
            })
            if (res.ok && newStatus === 'in_progress') {
                const body = await res.json()
                setDispatchStatus({ id, message: 'Dispatched successfully!' })
                setTimeout(() => setDispatchStatus(null), 3000)
            } else if (!res.ok) {
                if (newStatus === 'in_progress') setDispatchStatus(null)
            }
        } catch (err) {
            console.error(err)
            if (newStatus === 'in_progress') setDispatchStatus({ id, message: 'Dispatch failed' })
            setTimeout(() => setDispatchStatus(null), 3000)
            loadTasks()
        }
    }

    return (
        <div className="min-h-screen bg-[#070709] text-white p-6 md:p-12 font-sans relative overflow-x-hidden">
            <div className="fixed top-[-10%] right-[-5%] w-[40%] h-[40%] rounded-full bg-indigo-600/10 blur-[150px] pointer-events-none" />

            <div className="max-w-7xl mx-auto z-10 relative h-full flex flex-col">
                <header className="mb-8 border-b border-white/5 pb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                    <div>
                        <h1 className="text-4xl font-extrabold tracking-tight bg-gradient-to-r from-gray-200 to-gray-500 bg-clip-text text-transparent flex items-center gap-3 mb-2">
                            <ListTodo className="w-8 h-8 text-indigo-400" />
                            Kanban Board
                        </h1>
                        <p className="text-slate-400 text-lg">Manage OpenClaw tasks and agent runs visually.</p>
                    </div>
                    <div className="flex items-center gap-4 w-full md:w-auto">
                        <form onSubmit={handleCreateTask} className="flex flex-col sm:flex-row gap-2 flex-1 md:w-[480px]">
                            <div className="relative flex-1">
                                <input
                                    type="text"
                                    value={newTaskTitle}
                                    onChange={(e) => setNewTaskTitle(e.target.value)}
                                    placeholder="New task..."
                                    className="w-full bg-white/5 border border-white/10 rounded-full py-2.5 pl-5 pr-12 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500/50 shadow-inner"
                                    disabled={isAdding}
                                />
                                <button
                                    type="submit"
                                    disabled={!newTaskTitle.trim() || isAdding}
                                    className="absolute right-1 top-1 bottom-1 px-3 bg-indigo-500 hover:bg-indigo-400 disabled:bg-white/5 disabled:text-gray-600 rounded-full transition-colors flex items-center justify-center text-white"
                                >
                                    {isAdding ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
                                </button>
                            </div>
                            <select
                                value={newTaskSessionKey}
                                onChange={(e) => setNewTaskSessionKey(e.target.value)}
                                className="bg-white/5 border border-white/10 rounded-full py-2.5 px-4 text-sm text-gray-300 focus:outline-none focus:border-indigo-500/50 sm:w-auto w-full hidden sm:block truncate shrink-0 max-w-[150px]"
                                disabled={isAdding}
                                title="Default Agent Session"
                            >
                                <option value="agent:main:main" className="bg-[#131318]">agent:main:main</option>
                                {sessions.filter(s => s.sessionKey !== 'agent:main:main').map(s => (
                                    <option key={s.sessionKey} value={s.sessionKey} className="bg-[#131318]">{s.sessionKey}</option>
                                ))}
                            </select>
                        </form>
                        <a href="/agents" className="px-5 py-2.5 bg-white/5 hover:bg-white/10 rounded-full text-sm font-medium transition-colors border border-white/10 whitespace-nowrap hidden sm:block">
                            &larr; Agents
                        </a>
                    </div>
                </header>

                {loading && tasks.length === 0 ? (
                    <div className="flex justify-center py-20 flex-1">
                        <Loader2 className="w-8 h-8 animate-spin text-indigo-400" />
                    </div>
                ) : (
                    <div className="flex flex-col md:flex-row gap-6 items-start overflow-x-auto pb-4 custom-scrollbar snap-x flex-1">
                        {STATUSES.map(column => {
                            const columnTasks = tasks.filter(t => t.status === column.id)

                            return (
                                <div
                                    key={column.id}
                                    className={`min-w-[320px] w-full md:w-[320px] lg:flex-1 shrink-0 bg-[#0e0e12]/80 border rounded-3xl p-4 flex flex-col h-[65vh] md:h-[calc(100vh-250px)] snap-center backdrop-blur-xl transition-all duration-200 ${dragOverColumn === column.id
                                        ? 'border-indigo-500/60 ring-2 ring-indigo-500/20 bg-indigo-500/5'
                                        : 'border-white/5'
                                        }`}
                                    onDragOver={(e) => {
                                        e.preventDefault()
                                        e.dataTransfer.dropEffect = 'move'
                                        if (dragOverColumn !== column.id) setDragOverColumn(column.id)
                                    }}
                                    onDragLeave={(e) => {
                                        // Only clear if we're leaving the column entirely
                                        if (!e.currentTarget.contains(e.relatedTarget as Node)) {
                                            setDragOverColumn(null)
                                        }
                                    }}
                                    onDrop={(e) => {
                                        e.preventDefault()
                                        setDragOverColumn(null)
                                        const taskId = e.dataTransfer.getData('text/plain')
                                        if (taskId) {
                                            const task = tasks.find(t => t.id === taskId)
                                            if (task && task.status !== column.id) {
                                                handleUpdateStatus(taskId, column.id)
                                            }
                                        }
                                        setDraggedTaskId(null)
                                    }}
                                >
                                    <div className={`flex items-center justify-between p-3 rounded-2xl mb-4 ${column.color}`}>
                                        <h3 className="font-bold flex items-center gap-2">
                                            {column.icon} {column.label}
                                        </h3>
                                        <span className="bg-black/20 px-2 py-0.5 rounded-full text-xs font-bold text-inherit">{columnTasks.length}</span>
                                    </div>

                                    <div className="flex-1 overflow-y-auto space-y-3 custom-scrollbar pr-1 pb-1">
                                        {columnTasks.map(task => (
                                            <div
                                                key={task.id}
                                                draggable
                                                onDragStart={(e) => {
                                                    e.dataTransfer.setData('text/plain', task.id)
                                                    e.dataTransfer.effectAllowed = 'move'
                                                    setDraggedTaskId(task.id)
                                                }}
                                                onDragEnd={() => {
                                                    setDraggedTaskId(null)
                                                    setDragOverColumn(null)
                                                }}
                                                onClick={() => setSelectedTask(task)}
                                                className={`bg-white/5 hover:bg-white/10 border ${column.border} rounded-2xl p-4 cursor-grab active:cursor-grabbing transition-all duration-200 hover:scale-[1.02] active:scale-[0.98] shadow-sm flex flex-col gap-3 group ${draggedTaskId === task.id ? 'opacity-40 scale-95' : ''
                                                    }`}
                                            >
                                                <p className={`text-sm font-medium leading-relaxed ${task.status === 'done' ? 'line-through text-gray-500' : 'text-gray-200'}`}>
                                                    {task.title}
                                                </p>

                                                {(task.description || task.autoGenerated) && (
                                                    <div className="flex items-center justify-between text-xs mt-1">
                                                        {task.autoGenerated ? (
                                                            <span className="uppercase font-bold tracking-wider text-indigo-300 bg-indigo-500/20 px-2 flex items-center h-5 rounded shadow">
                                                                Auto
                                                            </span>
                                                        ) : <span />}

                                                        {task.description && (
                                                            <AlignLeft className="w-4 h-4 text-gray-500 group-hover:text-gray-400 transition-colors" />
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                        ))}
                                        {columnTasks.length === 0 && (
                                            <div className={`text-center py-8 text-sm border-2 border-dashed rounded-2xl transition-colors ${dragOverColumn === column.id
                                                ? 'border-indigo-500/30 text-indigo-400/50'
                                                : 'border-white/5 text-gray-600/50'
                                                }`}>
                                                {dragOverColumn === column.id ? 'Drop here' : 'No tasks'}
                                            </div>
                                        )}
                                    </div>
                                </div>
                            )
                        })}
                    </div>
                )}
            </div>

            {/* Task Detail Modal */}
            {selectedTask && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200" onClick={(e) => {
                    if (e.target === e.currentTarget) setSelectedTask(null)
                }}>
                    <div className="bg-[#131318] border border-white/10 w-full max-w-2xl rounded-3xl shadow-2xl flex flex-col max-h-[90vh]">
                        <div className="p-6 border-b border-white/5 flex justify-between items-start">
                            <div className="pr-4">
                                <h2 className="text-xl font-bold text-white/95 leading-tight">{selectedTask.title}</h2>
                                <div className="flex items-center gap-2 mt-3 font-mono text-[10px] md:text-xs text-slate-500 flex-wrap">
                                    <span className="bg-white/5 px-2 py-1 rounded max-w-[200px] truncate" title={selectedTask.id}>{selectedTask.id}</span>
                                    <span>•</span>
                                    <span>{new Date(selectedTask.createdAt).toLocaleString()}</span>
                                    {selectedTask.autoGenerated && (
                                        <>
                                            <span>•</span>
                                            <span className="text-indigo-400 font-bold bg-indigo-500/10 px-2 py-0.5 rounded">AUTO-GENERATED</span>
                                        </>
                                    )}
                                </div>
                            </div>
                            <button onClick={() => setSelectedTask(null)} className="p-2 bg-white/5 hover:bg-white/10 rounded-full transition-colors text-gray-400 hover:text-white shrink-0">
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <div className="p-6 select-text overflow-y-auto flex-1 text-sm custom-scrollbar bg-black/20">
                            <div className="mb-6">
                                <h4 className="uppercase text-xs font-bold text-gray-500 tracking-wider mb-2">Description</h4>
                                <div className="bg-black/30 border border-white/5 rounded-2xl p-4 text-gray-300 min-h-[100px] whitespace-pre-wrap leading-relaxed">
                                    {selectedTask.description || <span className="text-gray-600 italic">No description provided.</span>}
                                </div>
                            </div>

                            {(selectedTask.sourceRunId || selectedTask.sessionKey) && (
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                                    {selectedTask.sourceRunId && (
                                        <div className="bg-white/5 p-4 rounded-2xl border border-white/5">
                                            <p className="uppercase text-[10px] font-bold text-gray-500 tracking-wider mb-1">Source Run</p>
                                            <p className="font-mono text-indigo-300 text-xs break-words select-all">{selectedTask.sourceRunId}</p>
                                        </div>
                                    )}
                                    {selectedTask.sessionKey && (
                                        <div className="bg-white/5 p-4 rounded-2xl border border-white/5">
                                            <p className="uppercase text-[10px] font-bold text-gray-500 tracking-wider mb-1">Session Key</p>
                                            <p className="font-mono text-blue-300 text-xs break-words select-all">{selectedTask.sessionKey}</p>
                                        </div>
                                    )}
                                </div>
                            )}

                            {/* Agent Responses / Run Events */}
                            {selectedTask.sourceRunId && (
                                <div>
                                    <h4 className="uppercase text-xs font-bold text-gray-500 tracking-wider mb-3 flex items-center gap-2">
                                        Agent Answers & Logs
                                        {loadingEvents && <Loader2 className="w-3 h-3 animate-spin inline-block text-indigo-400" />}
                                    </h4>

                                    {!loadingEvents && selectedTaskEvents && selectedTaskEvents.length === 0 && (
                                        <div className="text-gray-500 italic text-sm p-4 bg-white/5 rounded-2xl border border-white/5">
                                            No readable responses found for this run.
                                        </div>
                                    )}

                                    {!loadingEvents && selectedTaskEvents && selectedTaskEvents.length > 0 && (
                                        <div className="space-y-3">
                                            {selectedTaskEvents.map((evt, idx) => {
                                                const text = evt.text;
                                                const isChat = evt.kind === 'chat';
                                                return (
                                                    <div key={evt.eventId || idx} className={`p-4 rounded-2xl border ${isChat ? 'bg-indigo-900/10 border-indigo-500/20' : 'bg-white/5 border-white/5'}`}>
                                                        <div className="flex items-center justify-between mb-2">
                                                            <span className={`text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded ${isChat ? 'bg-indigo-500/20 text-indigo-300' : 'bg-white/10 text-gray-400'}`}>
                                                                {evt.kind || 'log'}
                                                            </span>
                                                            <span className="text-xs text-gray-500 font-mono">
                                                                {new Date(evt.ts).toLocaleTimeString()}
                                                            </span>
                                                        </div>
                                                        <div className="text-gray-300 whitespace-pre-wrap leading-relaxed text-[13px] font-mono">
                                                            {text}
                                                        </div>
                                                    </div>
                                                )
                                            })}
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>

                        <div className="p-6 border-t border-white/5 bg-white/[0.02] flex flex-col gap-4">
                            {dispatchStatus?.id === selectedTask.id && (
                                <div className={`text-sm px-4 py-2 rounded-xl mb-2 text-center font-medium ${dispatchStatus.message.includes('success') ? 'bg-green-500/10 text-green-400 border border-green-500/20' : dispatchStatus.message.includes('fail') ? 'bg-red-500/10 text-red-400 border border-red-500/20' : 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 animate-pulse'}`}>
                                    {dispatchStatus.message}
                                </div>
                            )}
                            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                                <div className="flex items-center gap-3">
                                    <span className="text-sm font-medium text-gray-400 shrink-0">Move to:</span>
                                    {selectedTask.status === 'planned' && (
                                        <select
                                            value={newTaskSessionKey}
                                            onChange={(e) => setNewTaskSessionKey(e.target.value)}
                                            className="bg-black/30 border border-white/10 rounded-xl py-2 px-3 text-xs text-gray-300 focus:outline-none focus:border-indigo-500/50 max-w-[150px] truncate"
                                            title="Override Agent Session for Dispatch"
                                        >
                                            <option value="agent:main:main" className="bg-[#131318]">agent:main:main</option>
                                            {sessions.filter(s => s.sessionKey !== 'agent:main:main').map(s => (
                                                <option key={s.sessionKey} value={s.sessionKey} className="bg-[#131318]">{s.sessionKey}</option>
                                            ))}
                                        </select>
                                    )}
                                </div>
                                <div className="flex flex-wrap gap-2 sm:justify-end">
                                    {STATUSES.map(s => (
                                        <button
                                            key={s.id}
                                            onClick={() => handleUpdateStatus(selectedTask.id, s.id, (s.id === 'in_progress' && selectedTask.status === 'planned') ? newTaskSessionKey : undefined)}
                                            className={`px-3 py-2 rounded-xl text-[13px] font-semibold transition-all border outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-[#131318] ${selectedTask.status === s.id
                                                ? `${s.color} border-current shadow-md pointer-events-none opacity-50`
                                                : 'bg-white/5 text-gray-300 border-white/10 hover:bg-white/10 hover:text-white hover:border-white/20'
                                                }`}
                                        >
                                            {s.label}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
