export type GatewayFrame =
  | { type: 'req'; id: string; method: string; params?: unknown }
  | { type: 'res'; id: string; ok: boolean; payload?: unknown; error?: { code?: string; message?: string } }
  | { type: 'event'; event: string; payload?: unknown; seq?: number }
  | { type: 'hello-ok'; protocol?: number; snapshot?: unknown; features?: unknown }

export type MonitorSession = {
  sessionKey: string
  agentId: string
  channel: string
  status: 'idle' | 'active' | 'thinking'
  lastActivityAt: number
  spawnedBy?: string
}

export type MonitorRun = {
  runId: string
  sessionKey: string
  state: 'running' | 'final' | 'error' | 'aborted'
  startedAt: number
  endedAt?: number
  error?: string
  lastSeq?: number
}

export type MonitorEvent = {
  eventId: string
  runId: string
  sessionKey: string
  kind: 'chat' | 'agent' | 'exec' | 'system'
  stream?: string
  phase?: string
  toolName?: string
  state?: string
  seq?: number
  ts: number
  schemaVersion: number
  payload: unknown
}

export type MonitorExec = {
  execId: string
  runId?: string
  sessionKey?: string
  command: string
  status: 'running' | 'completed' | 'failed'
  exitCode?: number
  outputPreview?: string
  updatedAt: number
}

export type ParsedEnvelope = {
  session?: Partial<MonitorSession>
  run?: Partial<MonitorRun> & { runId: string; sessionKey?: string }
  event?: MonitorEvent
  exec?: MonitorExec
  rawEvent?: { event: string; payload?: unknown; seq?: number; ts: number }
}

export type Diagnostics = {
  connected: boolean
  reconnectAttempts: number
  parserErrors: number
  streamGaps: number
  droppedNoisyEvents: number
  queuedEvents: number
  lastError?: string
  lastConnectAt?: number
  lastDisconnectAt?: number
}

export type TaskStatus = 'planned' | 'in_progress' | 'waiting_approval' | 'review' | 'done'

export type TaskItem = {
  id: string
  title: string
  description?: string
  status: TaskStatus
  sourceRunId?: string
  sessionKey?: string
  autoGenerated: boolean
  createdAt: number
  updatedAt: number
  tags?: string[]
}
